jobs:
  include:
    - stage: test
      name: "Javascript functional tests"
      language: node_js
      node_js:
        - node
      env:
        - MOZ_HEADLESS=1
      addons:
        # download the latest Firefox binary from Mozilla and link the binary to /usr/local/bin/firefox
        firefox: latest
      script:
        # add geckodriver executable path to the PATH variable
        export PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/geckodriver/bin;
        yarn mocha --timeout 15000 test/functional/functionalTest.js;
      # language: node_js
      # node_js:
      #   - node
      # addons:
      #   apt:
      #     packages:
      #       - python-virtualenv
      # after_success:
      #   - "npm run coveralls"
    - stage: test
      name: "Javascript tests"
      language: node_js
      node_js:
        - node
      addons:
        apt:
          packages:
            - python-virtualenv
      after_success:
        - "npm run coveralls"
    - stage: test
      name: "Python 3.6 tests"
      language: python
      python:
        - "3.6"
      install:
        - pip install -e cli/
      script:
        - pytest cli/fathom_web/test
    - stage: test
      name: "Python 3.7 tests"
      dist: bionic
      language: python
      python:
        - "3.7"
      install:
        - pip install -e cli/
      script:
        - pytest cli/fathom_web/test
    - stage: deploy
      name: "Docs deployment"
      script: skip
      deploy:
        provider: script
        script: docs/tooling/travis-deploy-docs
        on:
          branch: master
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.mozilla.org#fathom"
    template:
      - "[%{repository_name} %{branch} %{result}] \"%{commit_subject}\" by %{author}"
      - "Changes: %{compare_url}"
      - "Build details: %{build_url}"

branches:
  only:
  - master

env:
  global:
    secure: HHQt4+1VlPYijt02kLcLRECv2F7+wyV/0SGyTJgwHK+95y+x/oDFvrPavgVo1RPBvvoUUAjBN1mZCdV/0UlcFMUgWksR6oj/3+HIux9a0aK/vb/m2Jb8r/rVR3YxwwYsc12l1ensPKpPyF08arMnOCMRcEYvOoWfGwrYiv2jSVqWjZOyPnO3nFyzliVOfTzU5H8409tyAMNUdkg5tjp/SwbzMkm9ijHxHHxTNP2HWkEUj/2rfQQnFzxKLlNkKoMVoVB3VJKBknDmm0/L++MoeMfbtLBgGr6pnzUAInUQRycJBx8iExTpogDZCOFJrrmxbDtYmHbc5LZ4S4XJhjMKE1fJwTx42QIGrstfrJcV+H4NhsbocgQO1ggtjKs3QqkqCih7vnPd4oh9NH9oK3SbMSMo92vYKMIXILthd529SRV4kkdNCPM2bj2DHM2PnE3po781b+PdwMqOUBAy5NJnNYuDweOFyxEA6xW8blONmZaEwgAfGqNZH73Fxdp2FGS6q2hKMloUIWWY/Ixp9HF9EaApxJxD3FcRtHovhlu4IboKzqVh+3b57jfMb9phLyTb9wTHLCRoVThoMl2gbK8K9MUmMzZjiflUpTTirzk5EHm1yQa+mRGp62glD1mLkYJHmGRbxmpCmrsadcohPGwbUNTXpAjsq3oGNe7h5bX7DOM=
